-- Add location visibility fields and mapping table to Finished Goods / Sales Items

-- 1. Alter hq_sale_items to add location_availability_mode
ALTER TABLE public.hq_sale_items
  ADD COLUMN IF NOT EXISTS location_availability_mode TEXT DEFAULT 'all'
  CHECK (location_availability_mode IN ('all', 'selected', 'hq_only'));

-- Update existing sale items to default to 'all' (defensive)
UPDATE public.hq_sale_items
  SET location_availability_mode = 'all'
  WHERE location_availability_mode IS NULL;

-- 2. Create the finished_good_location_availability junction table
CREATE TABLE IF NOT EXISTS public.finished_good_location_availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  finished_good_id TEXT NOT NULL REFERENCES public.hq_sale_items(id) ON DELETE CASCADE,
  location_id TEXT NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT finished_good_location_avail_unique UNIQUE (finished_good_id, location_id)
);

-- Indexing for lookup efficiency
CREATE INDEX IF NOT EXISTS finished_good_location_availability_fg_id_idx
  ON public.finished_good_location_availability(finished_good_id);

CREATE INDEX IF NOT EXISTS finished_good_location_availability_loc_id_idx
  ON public.finished_good_location_availability(location_id);

-- Enable RLS
ALTER TABLE public.finished_good_location_availability ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
DROP POLICY IF EXISTS "Finished Good Avail: HQ Admin manage" ON public.finished_good_location_availability;
CREATE POLICY "Finished Good Avail: HQ Admin manage"
  ON public.finished_good_location_availability
  FOR ALL
  USING (public.is_hq_admin_profile())
  WITH CHECK (public.is_hq_admin_profile());

DROP POLICY IF EXISTS "Finished Good Avail: Location Manager read own" ON public.finished_good_location_availability;
CREATE POLICY "Finished Good Avail: Location Manager read own"
  ON public.finished_good_location_availability
  FOR SELECT
  USING (public.is_location_manager_for(location_id));
